name: Compile SODAQ ExpLorRer Sketch

on:
  push:
    branches: [main, develop]
    paths:
      - "sodaq-explorer/**"
      - ".github/workflows/compile-sodaq.yml"
  pull_request:
    branches: [main]
    paths:
      - "sodaq-explorer/**"
      - ".github/workflows/compile-sodaq.yml"

jobs:
  compile-sodaq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install SODAQ SAMD platform
        run: |
          arduino-cli core update-index --additional-urls http://downloads.sodaq.net/package_sodaq_index.json
          arduino-cli core install SODAQ:samd --additional-urls http://downloads.sodaq.net/package_sodaq_index.json

      - name: Install Arduino AVR platform (if needed)
        run: |
          arduino-cli core install arduino:avr

      - name: Install required libraries
        run: |
          arduino-cli lib install "Sodaq_wdt"

      - name: Install custom libraries from lib folder
        run: |
          mkdir -p ~/Arduino/libraries
          if [ -d "./sodaq-explorer/lib" ]; then
            for dir in ./sodaq-explorer/lib/*/; do
              if [ -d "$dir" ]; then
                lib_name=$(basename "$dir")
                echo "Installing custom library: $lib_name"
                cp -r "$dir" ~/Arduino/libraries/
              fi
            done
          fi

      - name: List installed libraries
        run: arduino-cli lib list

      - name: Compile SODAQ sketch
        run: |
          arduino-cli compile --fqbn SODAQ:samd:sodaq_explorer ./sodaq-explorer/sodaq-explorer.ino --verbose

      - name: Upload compilation artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: sodaq-build
          path: |
            sodaq-explorer/**/*.bin
            sodaq-explorer/**/*.hex
            sodaq-explorer/**/*.elf

      - name: Check binary size
        run: |
          if [ -f "./sodaq-explorer/sodaq-explorer.ino.bin" ]; then
            size=$(stat -c%s "./sodaq-explorer/sodaq-explorer.ino.bin" 2>/dev/null || stat -f%z "./sodaq-explorer/sodaq-explorer.ino.bin")
            echo "SODAQ binary size: $size bytes"
          fi
